  deploy-service-a:
    needs: build-service-a
    runs-on: ubuntu-latest
    steps:
      - name: SSH ile sadece service-a'yı güncelle
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/mini-erp
            git fetch origin
            git reset --hard origin/main
            docker compose pull service-a
            docker compose up -d service-a

  deploy-service-b:
    needs: build-service-b
    runs-on: ubuntu-latest
    steps:
      - name: SSH ile sadece service-b'yi güncelle
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/mini-erp
            git fetch origin
            git reset --hard origin/main
            docker compose pull service-b
            docker compose up -d service-b